package leadActivities;

import org.apache.commons.lang.RandomStringUtils;
import org.openqa.selenium.By;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;
import com.selldo.POM.adminPages.AdminDashboardPage;
import com.selldo.POM.crm.LeadProfilePage;
import com.selldo.POM.crm.LoginPage;
import com.selldo.POM.crm.SiteVisitPage;
import com.selldo.Utility.BaseTest;

public class MarkingSiteVisitConductedTest extends BaseTest {

	@Test
	public void markingSiteVisitConductedTest() throws Exception {

		LoginPage login = new LoginPage(driver);
		login.login(prop.getProperty("AniketPreSaleUser"), prop.getProperty("password"));

		AdminDashboardPage adminDashboardPage = new AdminDashboardPage(driver);

		extentTest.get().log(Status.INFO, "Searching lead by Id.......");
		adminDashboardPage.searchLead(Integer.parseInt(R('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')),
				"All Leads");

		LeadProfilePage leadProfilePage = new LeadProfilePage(driver);

		extentTest.get().log(Status.INFO, "Clicking on Meeting Link.......");
		leadProfilePage.clickOnMeetingLink();

		//Thread.sleep(2000);

		SiteVisitPage siteVisitPage = new SiteVisitPage(driver);

		extentTest.get().log(Status.INFO, "Selecting Project from dropdown.........");
		siteVisitPage.selectProject();

		extentTest.get().log(Status.INFO, "Selecting date from Calender.........");
		siteVisitPage.selectDate();

		extentTest.get().log(Status.INFO, "Clicking on Site visit button.........");
		siteVisitPage.clickOnScheduleSiteVisitButton();

		// Thread.sleep(2000);

		if (!driver.findElements(By.xpath("//button[text()=' Ignore & Schedule ']")).isEmpty()) {
			try {
				siteVisitPage.clickOnIgnoreAndSchedule();
			} catch (Exception e) {
			}
		}
		String a = "Site visit for Visit scheduled successfully.";
		Assert.assertEquals(a, getSuccessMSG());
		// Thread.sleep(20000);

		extentTest.get().log(Status.INFO, "Selecting Mark As Conducted from Action Bar.......");
		leadProfilePage.selectMarkAsConducted();

		extentTest.get().log(Status.INFO, "Selecting date on which Site visit was conducted.......");
		siteVisitPage.sitevisitConductedOnDate2();

		extentTest.get().log(Status.INFO, "Writing some notes for conducted site visit.......");
		String exp = "Note Generated By Automation "+RandomStringUtils.randomAlphabetic(1000);
		siteVisitPage.enterNotesForConductedSiteVisit(exp);

		extentTest.get().log(Status.INFO, "Clicking on Mark as Conducted button.......");
		//siteVisitPage.clickOnMarkAsConductedButton();
		
		siteVisitPage.clickOnSaveButton();
		Assert.assertEquals("Site visit for Visit updated successfully.", getSuccessMSG());
		String text = leadProfilePage.clickOnFollowupNote() ;
		Assert.assertEquals(text, exp);
	}

}
