package Enums;

public enum Condition {
	Lead("Lead"),
	Status("Status"),
	Unread("Unread"),
	New_lead("New lead"),
	Touched("Touched"),
	Last_followup_status("Last followup status"),
	Last_followup_date("Last followup date"),
	Site_visit_status("Site visit status"),
	Followup_status("Followup status"),
	Last_incoming_call_status("Last incoming call status"),
	Last_outgoing_call_status("Last outgoing call status"),
	Latest_Activity_Scheduled_On("Latest Activity Scheduled On"),
	No_Future_Activity_On_Lead("No Future Activity On Lead"),
	Latest_Followup_Scheduled_On("Latest Followup Scheduled On"),
	Latest_Site_visit_Scheduled_On("Latest Site visit Scheduled On"),
	Last_contacted_by_Lead("Last contacted by Lead"),
	Last_Contact_attempted_by_Lead("Last Contact attempted by Lead"),
	Last_Contact_by_Sales("Last Contact by Sales"),
	Last_Contact_attempted_by_Sales("Last Contact attempted by Sales"),
	Last_Stage_Changed_On("Last Stage Changed On"),
	Last_Contact("Last Contact"),
	Last_acted_on("Last acted on"),
	Incoming_calls_Total("Incoming calls (Total)"),
	Outgoing_calls_Total("Outgoing calls (Total)"),
	Total_Answered_calls("Total Answered calls"),
	Total_Not_Answered_calls("Total Not-Answered calls"),
	Incoming_calls_Answered("Incoming calls (Answered)"),
	Incoming_calls_Not_Answered("Incoming calls (Not-Answered)"),
	Outgoing_calls_Answered("Outgoing calls (Answered)"),
	Outgoing_calls_Not_Answered("Outgoing calls (Not-Answered)"),
	Incoming_calls_Duration("Incoming calls (Duration)"),
	Outgoing_calls_Duration("Outgoing calls (Duration)"),
	Total_calls_Duration("Total calls (Duration)"),
	Quality("Quality"),
	Brochure_sent("Brochure sent"),
	Price_quote_sent("Price quote sent"),
	Currently_in("Currently in"),
	Min_budget("Min budget"),
	Max_budget("Max budget"),
	Min_possession("Min possession"),
	Max_possession("Max possession"),
	Location_preference("Location preference"),
	Property_type_preference("Property type preference"),
	BHK("BHK"),
	Transaction_type("Transaction type"),
	Interested_in_resale("Interested in resale"),
	Property_Purpose("Property Purpose"),
	Furnishing("Furnishing"),
	Facing("Facing"),
	Bathrooms("Bathrooms"),
	Funding_source("Funding source"),
	Developer("Developer"),
	Lead_Phone_Number_Verified("Lead Phone Number Verified"),
	Pending_incoming_mail("Pending incoming mail"),
	Pending_Incoming_Whatsapp_Messages_since_24_hrs("Pending Incoming Whatsapp Messages since 24 hrs"),
	Purpose("Purpose"),
	Reassigned_by("Reassigned by"),
	Reassigned_on("Reassigned on"),
	Reassigned_by_pre_sales("Reassigned by pre sales"),
	Transferred_from("Transferred from"),
	Country("Country"),
	Channel_Partner_ID("Channel Partner ID"),
	State("State"),
	City("City"),
	Nri("Nri"),
	Dropped_from_stage("Dropped from stage"),
	Drop_reason("Drop reason"),
	Stage_change_reason("Stage change reason"),
	Lead_Hotness("Lead Hotness"),
	Active("Active"),
	Lead_Primary_phone("Lead . Primary phone"),
	Lead_Primary_email("Lead . Primary email"),
	Sales("Sales"),
	Team("Team"),
	Presales_Pipeline_Stage("Presales - Pipeline Stage"),
	Sales_Pipeline_Stage("Sales - Pipeline Stage"),
	Presales_Sub_Status("Presales - Sub Status"),
	Sales_Sub_Status("Sales - Sub Status"),
	Validated_from_UI("Validated from UI"),
	Projects("Projects"),
	Campaigns("Campaigns"),
	Publisher("Publisher"),
	Sub_campaign("Sub campaign"),
	Medium_type("Medium type"),
	Medium_value("Medium value"),
	Form_Id("Form Id"),
	Lead_received_on("Lead received on"),
	Total_Site_visit_Scheduled("Total Site visit Scheduled"),
	Total_Site_visit_Conducted("Total Site visit Conducted"),
	Total_Site_visit_Missed("Total Site visit Missed"),
	Lead_Pipeline_Velocity("Lead Pipeline Velocity"),
	First_Project_Added("First Project Added"),
	Last_Project_Added("Last Project Added"),
	First_Campaign_Added("First Campaign Added"),
	Last_Campaign_Added("Last Campaign Added"),
	First_Source_Added("First Source Added"),
	Last_Source_Added("Last Source Added"),
	First_Sub_Source_Added("First Sub Source Added"),
	Last_Sub_Source_Added("Last Sub Source Added"),
	Custom_field_Qualified_Lead("Custom field - Qualified Lead");
	
	private String value;
	Condition(String str){
		this.value=str;
	}
	public String toString() {
		return value;
	}

}
