package POJO_Constant_GET;

public class ClientConfiguration {
    public boolean allow_direct_conduct_followup;
    public boolean allow_lead_assets;
    public boolean bulk_lead_reassign_access;
    public boolean bulk_lead_stage_change_access;
    public boolean call_summary_feedback;
    public boolean call_summery_popup;
    public boolean channel_partner;
    public boolean channel_partner_sales;
    public CustomUi custom_ui;
    public boolean detailed_lead_form_sales;
    public FeaturesEnabled features_enabled;
    public FollowupConfiguration followup_configuration;
    public boolean funnel_priority_report;
    public GpsConfiguration gps_configuration;
    public boolean individual_dashboard_call_stats;
    public boolean is_editable_pri_email;
    public boolean is_editable_pri_phone;
    public boolean is_editable_sec_emails;
    public boolean is_editable_sec_phones;
    public ArrayList<String> lead_merge_access;
    public LeadProfileRequiredFields lead_profile_required_fields;
    public LeadRequiredFields lead_required_fields;
    public boolean lock_stages;
    public MandatoryActivityAfterCall mandatory_activity_after_call;
    public boolean not_answered_call_summary_popup;
    public int offline_call_strategy;
    public boolean opt_in_enabled;
    public boolean pickup;
    public String pickup_locations;
    public PrimaryAddressRequiredFields primary_address_required_fields;
    public String reassign_lead_strategy;
    public boolean render_basic_ui;
    public RequirementRequiredFields requirement_required_fields;
    public SiteVisitConfiguration site_visit_configuration;
    public boolean team_based_access;
    public boolean team_management;
    public boolean phone_verification;
    public PostSalesConfiguration post_sales_configuration;
    public BookingFormConfiguration booking_form_configuration;
    public ExportConfiguration export_configuration;
}
