package POJO_Constant_GET;

public class CurrentUser {
	 public String authentication_token;
	    public String sales_id;
	    public String role;
	    public String department;
	    public String industry;
	    public boolean merge_leads;
	    public String id;
	    public String name;
	    public String first_name;
	    public String last_name;
	    public String time_zone;
	    public boolean gps_tracking_enabled;
	    public CallAvailabilities call_availabilities;
	    public ArrayList<Object> staff_ids;
	    public String team_id;
	    public boolean work_as_manager;
	    public String roaster;
	    public boolean allow_creating_leads;
	    public boolean allow_to_manage_leads;
	    public boolean assign_leads;
	    public Object roaster_sub_state;
	    public boolean custom_role_can_manage_tasks;
	    public boolean custom_role_can_bulk_reassign_lead;
	    public boolean custom_role_can_bulk_stage_change_lead;
	    public boolean custom_role_can_access_call_recording;
	    public boolean is_custom_role;
	    public boolean enable_voip;
	    public String email;
	    public String phone;
	    public String secondary_phone;
	    public PhoneCodes phone_codes;
	    public VoipCredentials voip_credentials;
	    public boolean is_post_sales_manager;
	    public boolean accessible_leads;
	    public boolean show_accessible_leads_option;
	    public Object custom_generic_user;
}
