package com.selldo.Utility;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;

public class demo extends BaseTest{
	Map<String,String> map ;

	public   void M1() throws IOException {
		driver.get("https://www.computerhope.com/htmcolor.htm");
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
		List<WebElement> code =driver.findElements(By.cssSelector("table[class='mtable2 tab nobreak'] td:first-child"));
		List<WebElement> name =driver.findElements(By.cssSelector("table[class='mtable2 tab nobreak'] td:nth-child(2)"));
		System.out.println("enum color {");
		for (int i = 0; i < code.size(); i++) {
			//System.out.println("map.put("+'"'+""+code.get(i).getText().trim()+""+'"'+","+""+'"'+""+ name.get(i).getText().trim()+""+'"'+");");
			String one = code.get(i).getText().trim();
			String two = name.get(i).getText().trim();
			System.out.println("map.put("+'"'+""+two+""+'"'+","+""+'"'+""+ one+""+'"'+");");
			
			//System.out.println(two.replaceAll(" ", "").replaceAll("((W3C))", "")+ ",");

		}
		System.out.println(";}");
//		XLUtils xu =new XLUtils(projectPath+"/colorCode.xlsx");
//		
//		for (int i = 0; i < code.size(); i++) {
//			for (int j = 0; j < code.size(); j++) {
//				xu.setCellData("Sheet1", i, 0, code.get(i).getText().trim());
//				xu.setCellData("Sheet1", i, 1, code.get(i).getText().trim());
//
//			}
//		
//			
//		}
		
	}
	public static void main(String[] args) {
		demo an = new demo();
		an.M2();
		an.M3();
		System.out.println();
	}
	public void M3() {
		System.out.println(map.get(color.AlienGreen));
		
	}
	public void M2(){
		map = new HashMap<String,String>();
		map.put("Black (W3C)","#000000");
		map.put("Night","#0C090A");
		map.put("Charcoal","#34282C");
		map.put("Oil","#3B3131");
		map.put("Dark Gray","#3A3B3C");
		map.put("Light Black","#454545");
		map.put("Black Cat","#413839");
		map.put("Iridium","#3D3C3A");
		map.put("Black Eel","#463E3F");
		map.put("Black Cow","#4C4646");
		map.put("Gray Wolf","#504A4B");
		map.put("Vampire Gray","#565051");
		map.put("Iron Gray","#52595D");
		map.put("Gray Dolphin","#5C5858");
		map.put("Carbon Gray","#625D5D");
		map.put("Ash Gray","#666362");
		map.put("DimGray or DimGrey (W3C)","#696969");
		map.put("Nardo Gray","#686A6C");
		map.put("Cloudy Gray","#6D6968");
		map.put("Smokey Gray","#726E6D");
		map.put("Alien Gray","#736F6E");
		map.put("Sonic Silver","#757575");
		map.put("Platinum Gray","#797979");
		map.put("Granite","#837E7C");
		map.put("Gray or Grey (W3C)","#808080");
		map.put("Battleship Gray","#848482");
		map.put("Gunmetal Gray","#8D918D");
		map.put("DarkGray or DarkGrey (W3C)","#A9A9A9");
		map.put("Gray Cloud","#B6B6B4");
		map.put("Silver (W3C)","#C0C0C0");
		map.put("Pale Silver","#C9C0BB");
		map.put("Gray Goose","#D1D0CE");
		map.put("Platinum Silver","#CECECE");
		map.put("LightGray or LightGrey (W3C)","#D3D3D3");
		map.put("Silver White","#DADBDD");
		map.put("Gainsboro (W3C)","#DCDCDC");
		map.put("Platinum","#E5E4E2");
		map.put("Metallic Silver","#BCC6CC");
		map.put("Blue Gray","#98AFC7");
		map.put("Roman Silver","#838996");
		map.put("LightSlateGray or LightSlateGrey (W3C)","#778899");
		map.put("SlateGray or SlateGrey (W3C)","#708090");
		map.put("Rat Gray","#6D7B8D");
		map.put("Slate Granite Gray","#657383");
		map.put("Jet Gray","#616D7E");
		map.put("Mist Blue","#646D7E");
		map.put("Marble Blue","#566D7E");
		map.put("Slate Blue Grey","#737CA1");
		map.put("Light Purple Blue","#728FCE");
		map.put("Azure Blue","#4863A0");
		map.put("Blue Jay","#2B547E");
		map.put("Charcoal Blue","#36454F");
		map.put("Dark Blue Grey","#29465B");
		map.put("Dark Slate","#2B3856");
		map.put("Deep-Sea Blue","#123456");
		map.put("Night Blue","#151B54");
		map.put("MidnightBlue (W3C)","#191970");
		map.put("Navy (W3C)","#000080");
		map.put("Denim Dark Blue","#151B8D");
		map.put("DarkBlue (W3C)","#00008B");
		map.put("Lapis Blue","#15317E");
		map.put("New Midnight Blue","#0000A0");
		map.put("Earth Blue","#0000A5");
		map.put("Cobalt Blue","#0020C2");
		map.put("MediumBlue (W3C)","#0000CD");
		map.put("Blueberry Blue","#0041C2");
		map.put("Canary Blue","#2916F5");
		map.put("Blue (W3C)","#0000FF");
		map.put("Samco Blue","#0002FF");
		map.put("Bright Blue","#0909FF");
		map.put("Blue Orchid","#1F45FC");
		map.put("Sapphire Blue","#2554C7");
		map.put("Blue Eyes","#1569C7");
		map.put("Bright Navy Blue","#1974D2");
		map.put("Balloon Blue","#2B60DE");
		map.put("RoyalBlue (W3C)","#4169E1");
		map.put("Ocean Blue","#2B65EC");
		map.put("Blue Ribbon","#306EFF");
		map.put("Blue Dress","#157DEC");
		map.put("Neon Blue","#1589FF");
		map.put("DodgerBlue (W3C)","#1E90FF");
		map.put("Glacial Blue Ice","#368BC1");
		map.put("SteelBlue (W3C)","#4682B4");
		map.put("Silk Blue","#488AC7");
		map.put("Windows Blue","#357EC7");
		map.put("Blue Ivy","#3090C7");
		map.put("Blue Koi","#659EC7");
		map.put("Columbia Blue","#87AFC7");
		map.put("Baby Blue","#95B9C7");
		map.put("CornflowerBlue (W3C)","#6495ED");
		map.put("Sky Blue Dress","#6698FF");
		map.put("Iceberg","#56A5EC");
		map.put("Butterfly Blue","#38ACEC");
		map.put("DeepSkyBlue (W3C)","#00BFFF");
		map.put("Midday Blue","#3BB9FF");
		map.put("Crystal Blue","#5CB3FF");
		map.put("Denim Blue","#79BAEC");
		map.put("Day Sky Blue","#82CAFF");
		map.put("LightSkyBlue (W3C)","#87CEFA");
		map.put("SkyBlue (W3C)","#87CEEB");
		map.put("Jeans Blue","#A0CFEC");
		map.put("Blue Angel","#B7CEEC");
		map.put("Pastel Blue","#B4CFEC");
		map.put("Light Day Blue","#ADDFFF");
		map.put("Sea Blue","#C2DFFF");
		map.put("Heavenly Blue","#C6DEFF");
		map.put("Robin Egg Blue","#BDEDFF");
		map.put("PowderBlue (W3C)","#B0E0E6");
		map.put("Coral Blue","#AFDCEC");
		map.put("LightBlue (W3C)","#ADD8E6");
		map.put("LightSteelBlue (W3C)","#B0CFDE");
		map.put("Gulf Blue","#C9DFEC");
		map.put("Pastel Light Blue","#D5D6EA");
		map.put("Lavender Blue","#E3E4FA");
		map.put("White Blue","#DBE9FA");
		map.put("Lavender (W3C)","#E6E6FA");
		map.put("Water","#EBF4FA");
		map.put("AliceBlue (W3C)","#F0F8FF");
		map.put("GhostWhite (W3C)","#F8F8FF");
		map.put("Azure (W3C)","#F0FFFF");
		map.put("LightCyan (W3C)","#E0FFFF");
		map.put("Light Slate","#CCFFFF");
		map.put("Electric Blue","#9AFEFF");
		map.put("Tron Blue","#7DFDFE");
		map.put("Blue Zircon","#57FEFF");
		map.put("Aqua or Cyan (W3C)","#00FFFF");
		map.put("Bright Cyan","#0AFFFF");
		map.put("Celeste","#50EBEC");
		map.put("Blue Diamond","#4EE2EC");
		map.put("Bright Turquoise","#16E2F5");
		map.put("Blue Lagoon","#8EEBEC");
		map.put("PaleTurquoise (W3C)","#AFEEEE");
		map.put("Pale Blue Lily","#CFECEC");
		map.put("Light Teal","#B3D9D9");
		map.put("Tiffany Blue","#81D8D0");
		map.put("Blue Hosta","#77BFC7");
		map.put("Cyan Opaque","#92C7C7");
		map.put("Northern Lights Blue","#78C7C7");
		map.put("Blue Green","#7BCCB5");
		map.put("MediumAquaMarine (W3C)","#66CDAA");
		map.put("Magic Mint","#AAF0D1");
		map.put("Light Aquamarine","#93FFE8");
		map.put("Aquamarine (W3C)","#7FFFD4");
		map.put("Bright Teal","#01F9C6");
		map.put("Turquoise (W3C)","#40E0D0");
		map.put("MediumTurquoise (W3C)","#48D1CC");
		map.put("Deep Turquoise","#48CCCD");
		map.put("Jellyfish","#46C7C7");
		map.put("Blue Turquoise","#43C6DB");
		map.put("DarkTurquoise (W3C)","#00CED1");
		map.put("Macaw Blue Green","#43BFC7");
		map.put("LightSeaGreen (W3C)","#20B2AA");
		map.put("Seafoam Green","#3EA99F");
		map.put("CadetBlue (W3C)","#5F9EA0");
		map.put("Deep-Sea","#3B9C9C");
		map.put("DarkCyan (W3C)","#008B8B");
		map.put("Teal Green","#00827F");
		map.put("Teal (W3C)","#008080");
		map.put("Teal Blue","#007C80");
		map.put("Medium Teal","#045F5F");
		map.put("Dark Teal","#045D5D");
		map.put("Deep Teal","#033E3E");
		map.put("DarkSlateGray or DarkSlateGrey (W3C)","#25383C");
		map.put("Gunmetal","#2C3539");
		map.put("Blue Moss Green","#3C565B");
		map.put("Beetle Green","#4C787E");
		map.put("Grayish Turquoise","#5E7D7E");
		map.put("Greenish Blue","#307D7E");
		map.put("Aquamarine Stone","#348781");
		map.put("Sea Turtle Green","#438D80");
		map.put("Dull-Sea Green","#4E8975");
		map.put("Dark Green Blue","#1F6357");
		map.put("Deep-Sea Green","#306754");
		map.put("Bottle Green","#006A4E");
		map.put("SeaGreen (W3C)","#2E8B57");
		map.put("Elf Green","#1B8A6B");
		map.put("Dark Mint","#31906E");
		map.put("Jade","#00A36C");
		map.put("Earth Green","#34A56F");
		map.put("Chrome Green","#1AA260");
		map.put("Emerald","#50C878");
		map.put("Mint","#3EB489");
		map.put("MediumSeaGreen (W3C)","#3CB371");
		map.put("Metallic Green","#7C9D8E");
		map.put("Camouflage Green","#78866B");
		map.put("Sage Green","#848B79");
		map.put("Hazel Green","#617C58");
		map.put("Venom Green","#728C00");
		map.put("OliveDrab (W3C)","#6B8E23");
		map.put("Olive (W3C)","#808000");
		map.put("DarkOliveGreen (W3C)","#556B2F");
		map.put("Military Green","#4E5B31");
		map.put("Green Leaves","#3A5F0B");
		map.put("Army Green","#4B5320");
		map.put("Fern Green","#667C26");
		map.put("Fall Forest Green","#4E9258");
		map.put("Irish Green","#08A04B");
		map.put("Pine Green","#387C44");
		map.put("Medium Forest Green","#347235");
		map.put("Jungle Green","#347C2C");
		map.put("Cactus Green","#227442");
		map.put("ForestGreen (W3C)","#228B22");
		map.put("Green (W3C)","#008000");
		map.put("DarkGreen (W3C)","#006400");
		map.put("Deep Green","#056608");
		map.put("Deep Emerald Green","#046307");
		map.put("Hunter Green","#355E3B");
		map.put("Dark Forest Green","#254117");
		map.put("Lotus Green","#004225");
		map.put("Seaweed Green","#437C17");
		map.put("Shamrock Green","#347C17");
		map.put("Green Onion","#6AA121");
		map.put("Moss Green","#8A9A5B");
		map.put("Grass Green","#3F9B0B");
		map.put("Green Pepper","#4AA02C");
		map.put("Dark Lime Green","#41A317");
		map.put("Parrot Green","#12AD2B");
		map.put("Clover Green","#3EA055");
		map.put("Dinosaur Green","#73A16C");
		map.put("Green Snake","#6CBB3C");
		map.put("Alien Green","#6CC417");
		map.put("Green Apple","#4CC417");
		map.put("LimeGreen (W3C)","#32CD32");
		map.put("Pea Green","#52D017");
		map.put("Kelly Green","#4CC552");
		map.put("Zombie Green","#54C571");
		map.put("Green Peas","#89C35C");
		map.put("Dollar Bill Green","#85BB65");
		map.put("Frog Green","#99C68E");
		map.put("Turquoise Green","#A0D6B4");
		map.put("DarkSeaGreen (W3C)","#8FBC8F");
		map.put("Basil Green","#829F82");
		map.put("Gray Green","#A2AD9C");
		map.put("Iguana Green","#9CB071");
		map.put("Citron Green","#8FB31D");
		map.put("Acid Green","#B0BF1A");
		map.put("Avocado Green","#B2C248");
		map.put("Pistachio Green","#9DC209");
		map.put("Salad Green","#A1C935");
		map.put("YellowGreen (W3C)","#9ACD32");
		map.put("Pastel Green","#77DD77");
		map.put("Hummingbird Green","#7FE817");
		map.put("Nebula Green","#59E817");
		map.put("Stoplight Go Green","#57E964");
		map.put("Neon Green","#16F529");
		map.put("Jade Green","#5EFB6E");
		map.put("Lime Mint Green","#36F57F");
		map.put("SpringGreen (W3C)","#00FF7F");
		map.put("MediumSpringGreen (W3C)","#00FA9A");
		map.put("Emerald Green","#5FFB17");
		map.put("Lime (W3C)","#00FF00");
		map.put("LawnGreen (W3C)","#7CFC00");
		map.put("Bright Green","#66FF00");
		map.put("Chartreuse (W3C)","#7FFF00");
		map.put("Yellow Lawn Green","#87F717");
		map.put("Aloe Vera Green","#98F516");
		map.put("Dull Green Yellow","#B1FB17");
		map.put("Lemon Green","#ADF802");
		map.put("GreenYellow (W3C)","#ADFF2F");
		map.put("Chameleon Green","#BDF516");
		map.put("Neon Yellow Green","#DAEE01");
		map.put("Yellow Green Grosbeak","#E2F516");
		map.put("Tea Green","#CCFB5D");
		map.put("Slime Green","#BCE954");
		map.put("Algae Green","#64E986");
		map.put("LightGreen (W3C)","#90EE90");
		map.put("Dragon Green","#6AFB92");
		map.put("PaleGreen (W3C)","#98FB98");
		map.put("Mint Green","#98FF98");
		map.put("Green Thumb","#B5EAAA");
		map.put("Organic Brown","#E3F9A6");
		map.put("Light Jade","#C3FDB8");
		map.put("Light Mint Green","#C2E5D3");
		map.put("Light Rose Green","#DBF9DB");
		map.put("Chrome White","#E8F1D4");
		map.put("HoneyDew (W3C)","#F0FFF0");
		map.put("MintCream (W3C)","#F5FFFA");
		map.put("LemonChiffon (W3C)","#FFFACD");
		map.put("Parchment","#FFFFC2");
		map.put("Cream","#FFFFCC");
		map.put("Cream White","#FFFDD0");
		map.put("LightGoldenRodYellow (W3C)","#FAFAD2");
		map.put("LightYellow (W3C)","#FFFFE0");
		map.put("Beige (W3C)","#F5F5DC");
		map.put("Cornsilk (W3C)","#FFF8DC");
		map.put("Blonde","#FBF6D9");
		map.put("Champagne","#F7E7CE");
		map.put("AntiqueWhite (W3C)","#FAEBD7");
		map.put("PapayaWhip (W3C)","#FFEFD5");
		map.put("BlanchedAlmond (W3C)","#FFEBCD");
		map.put("Bisque (W3C)","#FFE4C4");
		map.put("Wheat (W3C)","#F5DEB3");
		map.put("Moccasin (W3C)","#FFE4B5");
		map.put("Peach","#FFE5B4");
		map.put("Light Orange","#FED8B1");
		map.put("PeachPuff (W3C)","#FFDAB9");
		map.put("Coral Peach","#FBD5AB");
		map.put("NavajoWhite (W3C)","#FFDEAD");
		map.put("Golden Blonde","#FBE7A1");
		map.put("Golden Silk","#F3E3C3");
		map.put("Dark Blonde","#F0E2B6");
		map.put("Light Gold","#F1E5AC");
		map.put("Vanilla","#F3E5AB");
		map.put("Tan Brown","#ECE5B6");
		map.put("Dirty White","#E8E4C9");
		map.put("PaleGoldenRod (W3C)","#EEE8AA");
		map.put("Khaki (W3C)","#F0E68C");
		map.put("Cardboard Brown","#EDDA74");
		map.put("Harvest Gold","#EDE275");
		map.put("Sun Yellow","#FFE87C");
		map.put("Corn Yellow","#FFF380");
		map.put("Pastel Yellow","#FAF884");
		map.put("Neon Yellow","#FFFF33");
		map.put("Yellow (W3C)","#FFFF00");
		map.put("Canary Yellow","#FFEF00");
		map.put("Banana Yellow","#F5E216");
		map.put("Mustard Yellow","#FFDB58");
		map.put("Golden Yellow","#FFDF00");
		map.put("Bold Yellow","#F9DB24");
		map.put("Rubber Ducky Yellow","#FFD801");
		map.put("Gold (W3C)","#FFD700");
		map.put("Bright Gold","#FDD017");
		map.put("Chrome Gold","#FFCE44");
		map.put("Golden Brown","#EAC117");
		map.put("Deep Yellow","#F6BE00");
		map.put("Macaroni and Cheese","#F2BB66");
		map.put("Saffron","#FBB917");
		map.put("Neon Gold","#FDBD01");
		map.put("Beer","#FBB117");
		map.put("Yellow Orange or Orange Yellow","#FFAE42");
		map.put("Cantaloupe","#FFA62F");
		map.put("Cheese Orange","#FFA600");
		map.put("Orange (W3C)","#FFA500");
		map.put("Brown Sand","#EE9A4D");
		map.put("SandyBrown (W3C)","#F4A460");
		map.put("Brown Sugar","#E2A76F");
		map.put("Camel Brown","#C19A6B");
		map.put("Deer Brown","#E6BF83");
		map.put("BurlyWood (W3C)","#DEB887");
		map.put("Tan (W3C)","#D2B48C");
		map.put("Light French Beige","#C8AD7F");
		map.put("Sand","#C2B280");
		map.put("Sage","#BCB88A");
		map.put("Fall Leaf Brown","#C8B560");
		map.put("Ginger Brown","#C9BE62");
		map.put("Bronze Gold","#C9AE5D");
		map.put("DarkKhaki (W3C)","#BDB76B");
		map.put("Olive Green","#BAB86C");
		map.put("Brass","#B5A642");
		map.put("Cookie Brown","#C7A317");
		map.put("Metallic Gold","#D4AF37");
		map.put("Bee Yellow","#E9AB17");
		map.put("School Bus Yellow","#E8A317");
		map.put("GoldenRod (W3C)","#DAA520");
		map.put("Orange Gold","#D4A017");
		map.put("Caramel","#C68E17");
		map.put("DarkGoldenRod (W3C)","#B8860B");
		map.put("Cinnamon","#C58917");
		map.put("Peru (W3C)","#CD853F");
		map.put("Bronze","#CD7F32");
		map.put("Tiger Orange","#C88141");
		map.put("Copper","#B87333");
		map.put("Dark Gold","#AA6C39");
		map.put("Metallic Bronze","#A97142");
		map.put("Dark Almond","#AB784E");
		map.put("Wood","#966F33");
		map.put("Oak Brown","#806517");
		map.put("Antique Bronze","#665D1E");
		map.put("Hazel","#8E7618");
		map.put("Dark Yellow","#8B8000");
		map.put("Dark Moccasin","#827839");
		map.put("Khaki Green","#8A865D");
		map.put("Millennium Jade","#93917C");
		map.put("Dark Beige","#9F8C76");
		map.put("Bullet Shell","#AF9B60");
		map.put("Army Brown","#827B60");
		map.put("Sandstone","#786D5F");
		map.put("Taupe","#483C32");
		map.put("Mocha","#493D26");
		map.put("Milk Chocolate","#513B1C");
		map.put("Gray Brown","#3D3635");
		map.put("Dark Coffee","#3B2F2F");
		map.put("Old Burgundy","#43302E");
		map.put("Western Charcoal","#49413F");
		map.put("Bakers Brown","#5C3317");
		map.put("Dark Brown","#654321");
		map.put("Sepia Brown","#704214");
		map.put("Dark Bronze","#804A00");
		map.put("Coffee","#6F4E37");
		map.put("Brown Bear","#835C3B");
		map.put("Red Dirt","#7F5217");
		map.put("Sepia","#7F462C");
		map.put("Sienna (W3C)","#A0522D");
		map.put("SaddleBrown (W3C)","#8B4513");
		map.put("Dark Sienna","#8A4117");
		map.put("Sangria","#7E3817");
		map.put("Blood Red","#7E3517");
		map.put("Chestnut","#954535");
		map.put("Coral Brown","#9E4638");
		map.put("Chestnut Red","#C34A2C");
		map.put("Mahogany","#C04000");
		map.put("Red Gold","#EB5406");
		map.put("Red Fox","#C35817");
		map.put("Dark Bisque","#B86500");
		map.put("Light Brown","#B5651D");
		map.put("Petra Gold","#B76734");
		map.put("Rust","#C36241");
		map.put("Copper Red","#CB6D51");
		map.put("Orange Salmon","#C47451");
		map.put("Chocolate (W3C)","#D2691E");
		map.put("Sedona","#CC6600");
		map.put("Papaya Orange","#E56717");
		map.put("Halloween Orange","#E66C2C");
		map.put("Neon Orange","#FF6700");
		map.put("Bright Orange","#FF5F1F");
		map.put("Pumpkin Orange","#F87217");
		map.put("Carrot Orange","#F88017");
		map.put("DarkOrange (W3C)","#FF8C00");
		map.put("Construction Cone Orange","#F87431");
		map.put("Indian Saffron","#FF7722");
		map.put("Sunrise Orange","#E67451");
		map.put("Mango Orange","#FF8040");
		map.put("Coral (W3C)","#FF7F50");
		map.put("Basket Ball Orange","#F88158");
		map.put("Light Salmon Rose","#F9966B");
		map.put("LightSalmon (W3C)","#FFA07A");
		map.put("DarkSalmon (W3C)","#E9967A");
		map.put("Tangerine","#E78A61");
		map.put("Light Copper","#DA8A67");
		map.put("Salmon Pink","#FF8674");
		map.put("Salmon (W3C)","#FA8072");
		map.put("Peach Pink","#F98B88");
		map.put("LightCoral (W3C)","#F08080");
		map.put("Pastel Red","#F67280");
		map.put("Pink Coral","#E77471");
		map.put("Bean Red","#F75D59");
		map.put("Valentine Red","#E55451");
		map.put("IndianRed (W3C)","#CD5C5C");
		map.put("Tomato (W3C)","#FF6347");
		map.put("Shocking Orange","#E55B3C");
		map.put("OrangeRed (W3C)","#FF4500");
		map.put("Red (W3C)","#FF0000");
		map.put("Neon Red","#FD1C03");
		map.put("Scarlet Red","#FF2400");
		map.put("Ruby Red","#F62217");
		map.put("Ferrari Red","#F70D1A");
		map.put("Fire Engine Red","#F62817");
		map.put("Lava Red","#E42217");
		map.put("Love Red","#E41B17");
		map.put("Grapefruit","#DC381F");
		map.put("Cherry Red","#C24641");
		map.put("Chilli Pepper","#C11B17");
		map.put("FireBrick (W3C)","#B22222");
		map.put("Tomato Sauce Red","#B21807");
		map.put("Brown (W3C)","#A52A2A");
		map.put("Carbon Red","#A70D2A");
		map.put("Cranberry","#9F000F");
		map.put("Saffron Red","#931314");
		map.put("Crimson Red","#990000");
		map.put("Red Wine or Wine Red","#990012");
		map.put("DarkRed (W3C)","#8B0000");
		map.put("Maroon (W3C)","#800000");
		map.put("Burgundy","#8C001A");
		map.put("Vermilion","#7E191B");
		map.put("Deep Red","#800517");
		map.put("Red Blood","#660000");
		map.put("Blood Night","#551606");
		map.put("Dark Scarlet","#560319");
		map.put("Black Bean","#3D0C02");
		map.put("Chocolate Brown","#3F000F");
		map.put("Midnight","#2B1B17");
		map.put("Purple Lily","#550A35");
		map.put("Purple Maroon","#810541");
		map.put("Plum Pie","#7D0541");
		map.put("Plum Velvet","#7D0552");
		map.put("Dark Raspberry","#872657");
		map.put("Velvet Maroon","#7E354D");
		map.put("Rosy-Finch","#7F4E52");
		map.put("Dull Purple","#7F525D");
		map.put("Puce","#7F5A58");
		map.put("Rose Dust","#997070");
		map.put("Pastel Brown","#B1907F");
		map.put("Rosy Pink","#B38481");
		map.put("RosyBrown (W3C)","#BC8F8F");
		map.put("Khaki Rose","#C5908E");
		map.put("Lipstick Pink","#C48793");
		map.put("Pink Brown","#C48189");
		map.put("Old Rose","#C08081");
		map.put("Dusty Pink","#D58A94");
		map.put("Pink Daisy","#E799A3");
		map.put("Rose","#E8ADAA");
		map.put("Dusty Rose","#C9A9A6");
		map.put("Silver Pink","#C4AEAD");
		map.put("Gold Pink","#E6C7C2");
		map.put("Rose Gold","#ECC5C0");
		map.put("Deep Peach","#FFCBA4");
		map.put("Pastel Orange","#F8B88B");
		map.put("Desert Sand","#EDC9AF");
		map.put("Unbleached Silk","#FFDDCA");
		map.put("Pig Pink","#FDD7E4");
		map.put("Pale Pink","#F2D4D7");
		map.put("Blush","#FFE6E8");
		map.put("MistyRose (W3C)","#FFE4E1");
		map.put("Pink Bubble Gum","#FFDFDD");
		map.put("Light Rose","#FBCFCD");
		map.put("Light Red","#FFCCCB");
		map.put("Warm Pink","#F6C6BD");
		map.put("Deep Rose","#FBBBB9");
		map.put("Pink (W3C)","#FFC0CB");
		map.put("LightPink (W3C)","#FFB6C1");
		map.put("Soft Pink","#FFB8BF");
		map.put("Donut Pink","#FAAFBE");
		map.put("Baby Pink","#FAAFBA");
		map.put("Flamingo Pink","#F9A7B0");
		map.put("Pastel Pink","#FEA3AA");
		map.put("Rose Pink or Pink Rose","#E7A1B0");
		map.put("Cadillac Pink","#E38AAE");
		map.put("Carnation Pink","#F778A1");
		map.put("Pastel Rose","#E5788F");
		map.put("Blush Red","#E56E94");
		map.put("PaleVioletRed (W3C)","#DB7093");
		map.put("Purple Pink","#D16587");
		map.put("Tulip Pink","#C25A7C");
		map.put("Bashful Pink","#C25283");
		map.put("Dark Pink","#E75480");
		map.put("Dark Hot Pink","#F660AB");
		map.put("HotPink (W3C)","#FF69B4");
		map.put("Watermelon Pink","#FC6C85");
		map.put("Violet Red","#F6358A");
		map.put("Hot Deep Pink","#F52887");
		map.put("Bright Pink","#FF007F");
		map.put("DeepPink (W3C)","#FF1493");
		map.put("Neon Pink","#F535AA");
		map.put("Chrome Pink","#FF33AA");
		map.put("Neon Hot Pink","#FD349C");
		map.put("Pink Cupcake","#E45E9D");
		map.put("Royal Pink","#E759AC");
		map.put("Dimorphotheca Magenta","#E3319D");
		map.put("Pink Lemonade","#E4287C");
		map.put("Red Pink","#FA2A55");
		map.put("Raspberry","#E30B5D");
		map.put("Crimson (W3C)","#DC143C");
		map.put("Bright Maroon","#C32148");
		map.put("Rose Red","#C21E56");
		map.put("Rogue Pink","#C12869");
		map.put("Burnt Pink","#C12267");
		map.put("Pink Violet","#CA226B");
		map.put("Magenta Pink","#CC338B");
		map.put("MediumVioletRed (W3C)","#C71585");
		map.put("Dark Carnation Pink","#C12283");
		map.put("Raspberry Purple","#B3446C");
		map.put("Pink Plum","#B93B8F");
		map.put("Orchid (W3C)","#DA70D6");
		map.put("Deep Mauve","#DF73D4");
		map.put("Violet (W3C)","#EE82EE");
		map.put("Fuchsia Pink","#FF77FF");
		map.put("Bright Neon Pink","#F433FF");
		map.put("Fuchsia or Magenta (W3C)","#FF00FF");
		map.put("Crimson Purple","#E238EC");
		map.put("Heliotrope Purple","#D462FF");
		map.put("Tyrian Purple","#C45AEC");
		map.put("MediumOrchid (W3C)","#BA55D3");
		map.put("Purple Flower","#A74AC7");
		map.put("Orchid Purple","#B048B5");
		map.put("Rich Lilac","#B666D2");
		map.put("Pastel Violet","#D291BC");
		map.put("Mauve Taupe","#915F6D");
		map.put("Viola Purple","#7E587E");
		map.put("Eggplant","#614051");
		map.put("Plum Purple","#583759");
		map.put("Grape","#5E5A80");
		map.put("Purple Navy","#4E5180");
		map.put("SlateBlue (W3C)","#6A5ACD");
		map.put("Blue Lotus","#6960EC");
		map.put("Blurple","#5865F2");
		map.put("Light Slate Blue","#736AFF");
		map.put("MediumSlateBlue (W3C)","#7B68EE");
		map.put("Periwinkle Purple","#7575CF");
		map.put("Very Peri","#6667AB");
		map.put("Bright Grape","#6F2DA8");
		map.put("Purple Amethyst","#6C2DC7");
		map.put("Bright Purple","#6A0DAD");
		map.put("Deep Periwinkle","#5453A6");
		map.put("DarkSlateBlue (W3C)","#483D8B");
		map.put("Purple Haze","#4E387E");
		map.put("Purple Iris","#571B7E");
		map.put("Dark Purple","#4B0150");
		map.put("Deep Purple","#36013F");
		map.put("Midnight Purple","#2E1A47");
		map.put("Purple Monster","#461B7E");
		map.put("Indigo (W3C)","#4B0082");
		map.put("Blue Whale","#342D7E");
		map.put("RebeccaPurple (W3C)","#663399");
		map.put("Purple Jam","#6A287E");
		map.put("DarkMagenta (W3C)","#8B008B");
		map.put("Purple (W3C)","#800080");
		map.put("French Lilac","#86608E");
		map.put("DarkOrchid (W3C)","#9932CC");
		map.put("DarkViolet (W3C)","#9400D3");
		map.put("Purple Violet","#8D38C9");
		map.put("Jasmine Purple","#A23BEC");
		map.put("Purple Daffodil","#B041FF");
		map.put("Clematis Violet","#842DCE");
		map.put("BlueViolet (W3C)","#8A2BE2");
		map.put("Purple Sage Bush","#7A5DC7");
		map.put("Lovely Purple","#7F38EC");
		map.put("Neon Purple","#9D00FF");
		map.put("Purple Plum","#8E35EF");
		map.put("Aztech Purple","#893BFF");
		map.put("MediumPurple (W3C)","#9370DB");
		map.put("Light Purple","#8467D7");
		map.put("Crocus Purple","#9172EC");
		map.put("Purple Mimosa","#9E7BFF");
		map.put("Periwinkle","#CCCCFF");
		map.put("Pale Lilac","#DCD0FF");
		map.put("Lavender Purple","#967BB6");
		map.put("Rose Purple","#B09FCA");
		map.put("Lilac","#C8A2C8");
		map.put("Mauve","#E0B0FF");
		map.put("Bright Lilac","#D891EF");
		map.put("Purple Dragon","#C38EC7");
		map.put("Plum (W3C)","#DDA0DD");
		map.put("Blush Pink","#E6A9EC");
		map.put("Pastel Purple","#F2A2E8");
		map.put("Blossom Pink","#F9B7FF");
		map.put("Wisteria Purple","#C6AEC7");
		map.put("Purple Thistle","#D2B9D3");
		map.put("Thistle (W3C)","#D8BFD8");
		map.put("Purple White","#DFD3E3");
		map.put("Periwinkle Pink","#E9CFEC");
		map.put("Cotton Candy","#FCDFFF");
		map.put("Lavender Pinocchio","#EBDDE2");
		map.put("Dark White","#E1D9D1");
		map.put("Ash White","#E9E4D4");
		map.put("White Chocolate","#EDE6D6");
		map.put("Soft Ivory","#FAF0DD");
		map.put("Off White","#F8F0E3");
		map.put("Pearl White","#F8F6F0");
		map.put("Red White","#F3E8EA");
		map.put("LavenderBlush (W3C)","#FFF0F5");
		map.put("Pearl","#FDEEF4");
		map.put("Egg Shell","#FFF9E3");
		map.put("OldLace (W3C)","#FEF0E3");
		map.put("Linen (W3C)","#FAF0E6");
		map.put("SeaShell (W3C)","#FFF5EE");
		map.put("Bone White","#F9F6EE");
		map.put("Rice","#FAF5EF");
		map.put("FloralWhite (W3C)","#FFFAF0");
		map.put("Ivory (W3C)","#FFFFF0");
		map.put("White Gold","#FFFFF4");
		map.put("Light White","#FFFFF7");
		map.put("WhiteSmoke (W3C)","#F5F5F5");
		map.put("Cotton","#FBFBF9");
		map.put("Snow (W3C)","#FFFAFA");
		map.put("Milk White","#FEFCFF");
		map.put("Half White","#FFFEFA");
		map.put("White (W3C)","#FFFFFF");
		
	}

}